In [ ]:
# import pandas as pd
# import numpy as np

# df = pd.read_csv('current_normal.csv') 
# # df.head()
# # df.dtypes
# # df.isna()
# # df.info()
# # df.shape
# df[["Time"]]

                  Time
0      2021-09-01 0:04
1      2021-09-01 0:07
2      2021-09-01 0:10
3      2021-09-01 0:17
4      2021-09-01 0:21
...                ...
8197  2021-09-30 23:43
8198  2021-09-30 23:47
8199  2021-09-30 23:51
8200  2021-09-30 23:55
8201  2021-09-30 23:59

[8202 rows x 1 columns]

In [ ]:
df1 = pd.DataFrame({'이름': ['임동규','방시혁'], '나이': [20, 30]})
df2 = pd.DataFrame({'이름': ['강백호','홍서범'], '나이': [50, 40]})

pd.concat([df1, df2], ignore_index=True)

    이름  나이
0  임동규  20
1  방시혁  30
2  강백호  50
3  홍서범  40

In [89]:
df1 = pd.DataFrame({'이름': ['임동규','방시혁','박찬호'], '나이': [20, 30, 40]})
df2 = pd.DataFrame({'이름': ['임동규','방시혁','장미화'], '급여': [5000, 4000, 3000]})

# pd.merge(df1, df2, how='left')

q = pd.merge(df1, df2)
q1 = pd.merge(df1, df2, how='inner')
q2 = pd.merge(df1, df2, how='outer')

print(q)
print(q1)
print(q2)

    이름  나이    급여
0  임동규  20  5000
1  방시혁  30  4000
    이름  나이    급여
0  임동규  20  5000
1  방시혁  30  4000
    이름    나이      급여
0  박찬호  40.0     NaN
1  방시혁  30.0  4000.0
2  임동규  20.0  5000.0
3  장미화   NaN  3000.0

In [98]:
q2.sort_values(['이름'], ascending=False).reset_index(drop=True)

    이름    나이      급여
0  장미화   NaN  3000.0
1  임동규  20.0  5000.0
2  방시혁  30.0  4000.0
3  박찬호  40.0     NaN